version: '3.6'
services:
  open-elevation:
    container_name: open-elevation
    build:
      context: .
      dockerfile: ./docker/Dockerfile.arm64v8
    ports:
      - '8080:8080'
    volumes:
      - './data:/code/data'
